<?php
    // ### CONEXAO COM O BANCO DE DADOS MYSQL UTILIZANDO BIBLIOTECA MYSQLI ###
    // VOU UTILIZAR VARIAVEIS CONSTANTES PARA NÃO MODIFICAR O VALOR DURANTE A EXECUÇÃO DO SISTEMA

    define ("HOST", "localhost"); // CAMINHO DA CONEXAO COM O BANCO
    define ("USER", "root"); // NOME USUARIO DA CONEXAO
    define ("PASSWORD", ""); // SENHA DE CONEXAO COM O BANCO
    define ("DBNAME", "crud"); // NOME DO BANCO DE DADOS DA CONEXAO

    $conexao = mysqli_connect(HOST, USER, PASSWORD, DBNAME); // CONEXAO COM O BANCO PASSANDO OS VALORES

    mysqli_set_charset($conexao, "utf8"); // CODIFICAÇÃO DA CONEXÃO PARA UTF-8
?>